services:
  - type: web
    name: nmms-backend
    env: docker
    plan: free
    rootDir: backend
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://nmms-backend.onrender.com
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: nmms-db
          property: connectionString

databases:
  - name: nmms-db
    plan: free
